import type { NextPage } from 'next'
import Head from 'next/head'

//components
import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FirePoll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className="flex flex-col gap-2">
        <Hero />
      </main>
    </div>
  )
}

export default Home
