import type { NextPage } from 'next'
import Head from 'next/head'

//components
import Landing from '../components/Landing'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FirePoll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main  className="flex flex-col gap-2">
        <Landing />
      </main>
    </div>
  )
}

export default Home
